- type: paid-time-off
  details:
    duration: 20.00:00:00
    policy: YEARLY
- type: unpaid-time-off
  details:
    duration: 20.00:00:00
    policy: YEARLY
- type: family-leave
- type: bank-holiday
  details:
    days:
      - 2025-01-01
- type: custom-1
