// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odyssey.HRMS.Dal.SQLite;

#nullable disable

namespace Odyssey.HRMS.Dal.SQLite.Migrations
{
    [DbContext(typeof(JourneyDbContext))]
    [Migration("20250421123808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Odyssey.HRMS.Dal.SQLite.Entities.JourneyDal", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<long>("ChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("Odyssey.HRMS.Dal.SQLite.Entities.JourneyDal", b =>
                {
                    b.OwnsMany("Odyssey.HRMS.Dal.SQLite.Entities.JourneyActivityDal", "Activities", b1 =>
                        {
                            b1.Property<byte[]>("JourneyDalId")
                                .HasColumnType("BLOB");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("JourneyDalId", "__synthesizedOrdinal");

                            b1.ToTable("Journeys");

                            b1.ToJson("Activities");

                            b1.WithOwner()
                                .HasForeignKey("JourneyDalId");

                            b1.OwnsMany("Odyssey.HRMS.Dal.SQLite.Entities.JourneyActivityEventDal", "Events", b2 =>
                                {
                                    b2.Property<byte[]>("JourneyActivityDalJourneyDalId")
                                        .HasColumnType("BLOB");

                                    b2.Property<int>("JourneyActivityDal__synthesizedOrdinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid?>("NextActivityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("JourneyActivityDalJourneyDalId", "JourneyActivityDal__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Journeys");

                                    b2.WithOwner()
                                        .HasForeignKey("JourneyActivityDalJourneyDalId", "JourneyActivityDal__synthesizedOrdinal");
                                });

                            b1.Navigation("Events");
                        });

                    b.OwnsOne("Odyssey.HRMS.Dal.SQLite.Entities.JourneyStartupDal", "Startup", b1 =>
                        {
                            b1.Property<byte[]>("JourneyDalId")
                                .HasColumnType("BLOB");

                            b1.Property<string>("RepeatingRule")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("StartAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("JourneyDalId");

                            b1.ToTable("Journeys");

                            b1.ToJson("Startup");

                            b1.WithOwner()
                                .HasForeignKey("JourneyDalId");
                        });

                    b.OwnsOne("System.Collections.Generic.Dictionary<string, System.Text.Json.JsonElement>", "InitializationData", b1 =>
                        {
                            b1.Property<byte[]>("JourneyDalId")
                                .HasColumnType("BLOB");

                            b1.HasKey("JourneyDalId");

                            b1.ToTable("Journeys");

                            b1.ToJson("InitializationData");

                            b1.WithOwner()
                                .HasForeignKey("JourneyDalId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("InitializationData");

                    b.Navigation("Startup");
                });
#pragma warning restore 612, 618
        }
    }
}
